# Matrices
Una matris es un arreglo rectangular de escalares (es decir cualquier numero:entero, real o complejo) dispuestos en filas y columnas, por ejemplo:

$$\begin{bmatrix} 10 & 20 & 30 \\ 40 & 50 & 60 \end{bmatrix}$$

Tambien puedes pensar en una matriz como una lista de vectorees: la matriz anterior contiene 2 vectores 3D horizontales o 3 vectores de 2D verticales.

Las matroces son convenientes y muy eficientes para ejecutar operaciones en muchos vectores a la vez. Tambie veremos que son exelentes para representar y realizar transformaciones lineales como rotacionnes, traslaciones y cambios de escala.

## Matrices en Python 
En python, una matriz se puede representar de varias formas. El mas simple es solo una lista de listas de python:

In [1]:
[
    [10, 20, 30],
    [40, 50, 60]
]

[[10, 20, 30], [40, 50, 60]]

Pero al igual que los vectores, es mucho mejor representarlos como arreglos Numpy

In [2]:
import numpy as np
A = np.array([
    [10,20,30],
    [40,50,60]
])
print(A)

[[10 20 30]
 [40 50 60]]


Por convension, las matrices generalmente tienen nombres en mayuscula, como $A$.

En el resto de este tutorial, asumiremos que estasmos usando arreglos de Numpy (tipo `ndarray`) para representar matrices.

## Tamanio
El tamanio de una matriz se define por su numero de filas y numero de columnas. Se anota $filas \times columnas$. Por ejemplo, la matriz $A$ anterior es un ejemplo de una matriz de $2 \times 3$: 2 filas , 3 columnas. Precaucion: una matriz de $3 \times 2$ tendria 3 filas y 2 columnas.

Para obtener el tamanio de una matriz en Numpy: 

In [3]:
A.shape

(2, 3)

**Precaucion**: el atributo `size` representa el numero de lementos en el `ndarray`, no el tamanio de la matriz:

In [4]:
A.size

6

## Indexacion de elementos 
El numero ubicado en la fila $i^{th}$ y la columna $j^{th}$ de una matriz $X$ a veces se indica como $X_{i,j}$ o $X_{ij}$, pero no no es una notación estándar, por lo que la gente suele preferir nombrar explícitamente los elementos, así: "*Sea $X = (x_{i,j})_{1 ≤ i ≤ m, 1 ≤ j ≤ n}$*". Esto significa que $X$ es igual a:

$X = \begin{bmatrix}
   x_{1,1} & x_{1,2} & x_{1,3} & \cdots & x_{1,n}\\
   x_{2,1} & x_{2,2} & x_{2,3} & \cdots & x_{2,n}\\
   x_{3,1} & x_{3,2} & x_{3,3} & \cdots & x_{3,n}\\
   \vdots & \vdots & \vdots & \ddots & \vdots \\
   x_{m,1} & x_{m,2} & x_{m,3} & \cdots & x_{m,n}\\
\end{bmatrix}$

Sin embargo, en este notebook usaremos la notación $X_{i,j}$, ya que coincide bastante bien con la notación de NumPy. Tenga en cuenta que en matemáticas, los índices generalmente comienzan en 1, pero en programación generalmente comienzan en 0. Entonces, para acceder a $A_{2,3}$ mediante programación, debemos escribir esto:

In [5]:
A[1,2]  # 2da fila, 3ra columna

60

El vector de  la fila $i^{ésima}$ a veces se anota como $M_i$ o $M_{i,*}$, pero nuevamente no hay una notación estándar, por lo que las personas prefieren definir explícitamente sus propios nombres, por ejemplo: "*Sea **x**$_{i}$ el $i^{ésimo}$ vector fila  de la matriz $X$*". Usaremos $M_{i,*}$, por la misma razón que la anterior. Por ejemplo, para acceder a $A_{2,*}$ (es decir, el vector de la segunda fila de $A$):

In [6]:
A[1, :]  # Vector de segunda fila (como una matriz 1D)

array([40, 50, 60])

De manera similar, el $j^{ésimo}$ vector de columna a veces se indica como $M^j$ o $M_{*,j}$, pero no existe una notación estándar. Usaremos $M_{*,j}$. Por ejemplo, para acceder a $A_{*,3}$ (es decir, el vector de la tercera columna de $A$):

In [7]:
A[:, 2]  # 3er vector de columna (como una matriz 1D)

array([30, 60])

Tenga en cuenta que el resultado es en realidad una matriz NumPy unidimensional: no existe una matriz unidimensional *vertical* u *horizontal*. Si realmente necesita representar un vector de fila como una matriz de una fila (es decir, una matriz 2D NumPy), o un vector de columna como una matriz de una columna, entonces necesita usar un slice en lugar de un índice al acceder a la fila o columna, por ejemplo:

In [8]:
A[1:2, :]  # filas 2 a 3 (excluidas): esto devuelve la fila 2 como una matriz de una fila

array([[40, 50, 60]])

In [ ]:
A[:, 2:3]  # columnas 3 a 4 (excluidas): esto devuelve la columna 3 como una matriz de una columna 

## Matrices cuadradas, triangulares, diagonales e identidad

Una **matriz cuadrada** es una matriz que tiene el mismo número de filas y columnas, por ejemplo, una matriz de $3 \times 3$:

\begin{bmatrix}
  4 & 9 & 2 \\
  3 & 5 & 7 \\
  8 & 1 & 6
\end{bmatrix}

Una **matriz triangular superior** es un tipo especial de matriz cuadrada donde todos los elementos *debajo* de la diagonal principal (de arriba a la izquierda a abajo a la derecha) son cero, por ejemplo:

\begin{bmatrix}
  4 & 9 & 2 \\
  0 & 5 & 7 \\
  0 & 0 & 6
\end{bmatrix}

De manera similar, una **matriz triangular inferior** es una matriz cuadrada donde todos los elementos *encima* de la diagonal principal son cero, por ejemplo:

\begin{bmatrix}
  4 & 0 & 0 \\
  3 & 5 & 0 \\
  8 & 1 & 6
\end{bmatrix}

Una **matriz triangular** es una que es triangular inferior o triangular superior.

Una matriz que es tanto triangular superior como inferior se denomina **matriz diagonal**, por ejemplo:

\begin{bmatrix}
  4 & 0 & 0 \\
  0 & 5 & 0 \\
  0 & 0 & 6
\end{bmatrix}

Puede construir una matriz diagonal usando la función `diag` de NumPy:

In [9]:
np.diag([4, 5, 6])

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

Si pasa una matriz a la función `diag`, felizmente extraerá los valores diagonales:

In [10]:
D = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
    ])
np.diag(D)

array([1, 5, 9])

Finalmente, la **matriz identidad** de tamaño $n$, indicada como $I_n$, es una matriz diagonal de tamaño $n \times n$ con $1$ en la diagonal principal, por ejemplo $I_3$:

\begin{bmatrix}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
\end{bmatrix}

La función `eye` de Numpy devuelve la matriz de identidad del tamaño deseado:

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

La matriz de identidad a menudo se indica simplemente como $I$ (en lugar de $I_n$) cuando su tamaño es claro dado el contexto. Se llama la matriz *identidad* porque al multiplicar una matriz con ella, la matriz permanece sin cambios, como veremos a continuación.

## Sumando matrices
Si dos matrices $Q$ y $R$ tienen el mismo tamaño $m \times n$, se pueden sumar. La suma se realiza *elemento a elemento*: el resultado también es una matriz $m \times n$ $S$ donde cada elemento es la suma de los elementos en la posición correspondiente: $S_{i,j} = Q_{i,j} + R_{i,j}$

$$S =
\begin{bmatrix}
  Q_{11} + R_{11} & Q_{12} + R_{12} & Q_{13} + R_{13} & \cdots & Q_{1n} + R_{1n} \\
  Q_{21} + R_{21} & Q_{22} + R_{22} & Q_{23} + R_{23} & \cdots & Q_{2n} + R_{2n}  \\
  Q_{31} + R_{31} & Q_{32} + R_{32} & Q_{33} + R_{33} & \cdots & Q_{3n} + R_{3n}  \\
  \vdots & \vdots & \vdots & \ddots & \vdots \\
  Q_{m1} + R_{m1} & Q_{m2} + R_{m2} & Q_{m3} + R_{m3} & \cdots & Q_{mn} + R_{mn}  \\
\end{bmatrix}$$

Por ejemplo, creemos una matriz de $2 \times 3$ $B$ y calculemos $A + B$:

In [12]:
B = np.array([[1,2,3], [4, 5, 6]])
B

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
A

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
A + B

array([[11, 22, 33],
       [44, 55, 66]])

**La suma es *conmutativa***, lo que significa que $A + B = B + A$:

In [15]:
B + A

array([[11, 22, 33],
       [44, 55, 66]])

**También es *asociativo***, lo que significa que $A + (B + C) = (A + B) + C$:

In [16]:
C = np.array([[100,200,300], [400, 500, 600]])

A + (B + C)

array([[111, 222, 333],
       [444, 555, 666]])

In [17]:
(A + B) + C

array([[111, 222, 333],
       [444, 555, 666]])

## Multiplicación por un escalar
Una matriz $M$ se puede multiplicar por un escalar $\lambda$. El resultado se anota $\lambda M$, y es una matriz del mismo tamaño que $M$ con todos los elementos multiplicados por $\lambda$:

$$\lambda M =
\begin{bmatrix}
  \lambda \times M_{11} & \lambda \times M_{12} & \lambda \times M_{13} & \cdots & \lambda \times M_{1n} \\
  \lambda \times M_{21} & \lambda \times M_{22} & \lambda \times M_{23} & \cdots & \lambda \times M_{2n} \\
  \lambda \times M_{31} & \lambda \times M_{32} & \lambda \times M_{33} & \cdots & \lambda \times M_{3n} \\
  \vdots & \vdots & \vdots & \ddots & \vdots \\
  \lambda \times M_{m1} & \lambda \times M_{m2} & \lambda \times M_{m3} & \cdots & \lambda \times M_{mn} \\
\end{bmatrix}$$

Una forma más concisa de escribir esto es:

$(\lambda M)_{i,j} = \lambda (M)_{i,j}$

En NumPy, simplemente use el operador `*` para multiplicar una matriz por un escalar. Por ejemplo:

In [ ]:
2 * A

La multiplicación escalar también se define en el lado derecho y da el mismo resultado: $M \lambda = \lambda M$. Por ejemplo:

In [ ]:
A * 2

Esto hace que la multiplicación escalar sea **conmutativa**.

También es **asociativa**, lo que significa que $\alpha (\beta M) = (\alpha \times \beta) M$, donde $\alpha$ y $\beta$ son escalares. Por ejemplo:

In [ ]:
2 * (3 * A)

In [ ]:
(2 * 3) * A

Finalmente, es **distributiva sobre la suma** de matrices, lo que significa que $\lambda (Q + R) = \lambda Q + \lambda R$:

In [ ]:
2 * (A + B)

In [ ]:
2 * A + 2 * B

## Multiplicación de matrices
Hasta ahora, las operaciones matriciales han sido bastante intuitivas. Pero multiplicar matrices es un poco más complicado.

Una matriz $Q$ de tamaño $m \times n$ se puede multiplicar por una matriz $R$ de tamaño $n \times q$. Se anota simplemente $QR$ sin signo de multiplicación ni punto. El resultado $P$ es una matriz $m \times q$ donde cada elemento se calcula como una suma de productos:

$$P_{i,j} = \sum_{k=1}^n{Q_{i,k} \times R_{k,j}}$$

El elemento en la posición $i,j$ en la matriz resultante es la suma de los productos de los elementos en la fila $i$ de la matriz $Q$ por los elementos en la columna $j$ de la matriz $R$.

![Alt Text](https://numbas.mathcentre.ac.uk/media/question-resources/Matrix_Multiplication_02.gif)


Puedes notar que cada elemento $P_{i,j}$ es el producto escalar del vector fila $Q_{i,*}$ y el vector columna $R_{*,j}$:

$$P_{i,j} = Q_{i,*} \cdot R_{*,j}$$

Entonces podemos reescribir $P$ de manera más concisa como:

$$P =
\begin{bmatrix}
Q_{1,*} \cdot R_{*,1} & Q_{1,*} \cdot R_{*,2} & \cdots & Q_{1,*} \cdot R_{*,q} \\
Q_{2,*} \cdot R_{*,1} & Q_{2,*} \cdot R_{*,2} & \cdots & Q_{2,*} \cdot R_{*,q} \\
\vdots & \vdots & \ddots & \vdots \\
Q_{m,*} \cdot R_{*,1} & Q_{m,*} \cdot R_{*,2} & \cdots & Q_{m,*} \cdot R_{*,q}
\end{bmatrix}$$

Multipliquemos dos matrices en NumPy, usando el método `dot` de `ndarray`:
$$E = AD = \begin{bmatrix}
  10 & 20 & 30 \\
  40 & 50 & 60
\end{bmatrix} 
\begin{bmatrix}
  2 & 3 & 5 & 7 \\
  11 & 13 & 17 & 19 \\
  23 & 29 & 31 & 37
\end{bmatrix} = 
\begin{bmatrix}
  930 & 1160 & 1320 & 1560 \\
  2010 & 2510 & 2910 & 3450
\end{bmatrix}$$

In [18]:
D = np.array([
        [ 2,  3,  5,  7],
        [11, 13, 17, 19],
        [23, 29, 31, 37]
    ])
E = A.dot(D)
E

array([[ 930, 1160, 1320, 1560],
       [2010, 2510, 2910, 3450]])

Verifiquemos este resultado mirando un elemento, solo para estar seguros: mirando $E_{2,3}$ por ejemplo, necesitamos multiplicar los elementos en la $2^{da}$ fila de $A$ por los elementos en la $3^{ra}$ columna de D y suma estos productos:

In [19]:
40*5 + 50*17 + 60*31

2910

In [20]:
E[1,2]  # fila 2, columna 3

2910

¡Se ve bien! Puedes comprobar los otros elementos hasta que te acostumbres al algoritmo.

Multiplicamos una matriz de $2 \times 3$ por una matriz de $3 \times 4$, por lo que el resultado es una matriz de $2 \times 4$. El número de columnas de la primera matriz tiene que ser igual al número de filas de la segunda matriz. Si intentamos multiplicar $D$ por $A$, obtenemos un error porque D tiene 4 columnas mientras que A tiene 2 filas:

In [21]:
try:
    D.dot(A)
except ValueError as e:
    print("ValueError:", e)

ValueError: shapes (3,4) and (2,3) not aligned: 4 (dim 1) != 2 (dim 0)


Esto ilustra el hecho de que **la multiplicación de matrices *NO* es conmutativa**: en general $QR ≠ RQ$

De hecho, $QR$ y $RQ$ solo están *ambos* definidos si $Q$ tiene el tamaño $m \times n$ y $R$ tiene el tamaño $n \times m$. Veamos un ejemplo en el que ambos *están* definidos y mostramos que (en general) *NO* son iguales:

In [23]:
F = np.array([
        [5,2],
        [4,1],
        [9,3]
    ])
A.dot(F)

array([[400, 130],
       [940, 310]])